/* TOEIC 800-990点レベル 単語データ
 * 形式: [英単語, 品詞, 意味, 例文, 例文訳]
 * 単語を追加するときは、この配列に1行ずつ足してください。
 */
const WORDS_DATA = [
  ["accolade", "名", "称賛、栄誉", "The chef has received many accolades.", "そのシェフは数々の賞賛を受けてきた。"],
  ["accrue", "動", "（利息・費用が）発生する、たまる", "Interest will accrue on the unpaid balance.", "未払い残高には利息が発生します。"],
  ["acquisition", "名", "買収、取得", "The acquisition was completed in May.", "買収は5月に完了した。"],
  ["adamant", "形", "断固とした、譲らない", "She was adamant that the deadline be met.", "彼女は締め切りを守るよう強く主張した。"],
  ["adept", "形", "熟達した、上手な", "He is adept at handling difficult clients.", "彼は難しい顧客への対応が上手だ。"],
  ["adhere", "動", "（規則を）守る、固守する", "All staff must adhere to the dress code.", "全スタッフは服装規定を守らなければならない。"],
  ["adjourn", "動", "（会議を）休会する、中断する", "The meeting was adjourned until Monday.", "会議は月曜日まで休会となった。"],
  ["advent", "名", "到来、出現", "The advent of online banking changed the industry.", "ネットバンキングの登場が業界を変えた。"],
  ["adverse", "形", "不利な、有害な", "The storm had an adverse effect on sales.", "嵐は売上に悪影響を及ぼした。"],
  ["affiliate", "名", "関連会社、系列会社", "Our Osaka affiliate handles regional sales.", "大阪の関連会社が地域の販売を担当している。"],
  ["aggregate", "形", "合計の、総計の", "Aggregate demand rose by five percent.", "総需要は5%増加した。"],
  ["alleviate", "動", "（苦痛・問題を）和らげる", "The new hires will alleviate the workload.", "新規採用者によって業務量が軽くなる。"],
  ["allocate", "動", "割り当てる、配分する", "Funds were allocated to the new project.", "資金が新規プロジェクトに割り当てられた。"],
  ["amenable", "形", "（提案を）受け入れる余地がある", "The client seemed amenable to our terms.", "顧客はこちらの条件に前向きな様子だった。"],
  ["amortize", "動", "（負債を）分割償還する、償却する", "The loan will be amortized over ten years.", "そのローンは10年かけて償還される。"],
  ["ample", "形", "十分な、豊富な", "There is ample parking behind the building.", "建物の裏に十分な駐車スペースがある。"],
  ["annex", "名", "別館、付属建物", "The seminar will be held in the annex.", "セミナーは別館で開催される。"],
  ["appraisal", "名", "評価、査定", "Annual performance appraisals take place in March.", "年次の人事評価は3月に行われる。"],
  ["apprehensive", "形", "不安な、心配している", "Investors are apprehensive about the market.", "投資家は市場に不安を抱いている。"],
  ["apprise", "動", "（人に）知らせる", "Please keep me apprised of any changes.", "変更があれば随時お知らせください。"],
  ["arbitrary", "形", "恣意的な、気まぐれな", "The selection process should not be arbitrary.", "選考過程は恣意的であってはならない。"],
  ["arbitration", "名", "仲裁", "Both parties agreed to settle the dispute through arbitration.", "両者は仲裁で紛争を解決することに合意した。"],
  ["array", "名", "ずらりと並んだもの、多数", "The store offers a wide array of products.", "その店は幅広い商品を取りそろえている。"],
  ["articulate", "動", "（考えを）はっきり述べる", "She articulated her vision for the company.", "彼女は会社の将来像を明確に述べた。"],
  ["ascertain", "動", "確かめる、突き止める", "We need to ascertain the cause of the delay.", "遅延の原因を突き止める必要がある。"],
  ["attest", "動", "証明する、裏付ける", "Our sales figures attest to the product's popularity.", "売上の数字が製品の人気を裏付けている。"],
  ["attrition", "名", "（人員の）自然減", "Staff numbers will be reduced through attrition.", "人員は自然減によって削減される。"],
  ["audit", "名", "監査", "An external audit is scheduled for next month.", "来月、外部監査が予定されている。"],
  ["augment", "動", "増やす、増強する", "He took a second job to augment his income.", "彼は収入を増やすために副業を始めた。"],
  ["authorize", "動", "認可する、権限を与える", "Only managers can authorize refunds.", "返金を認可できるのは管理職だけだ。"],
  ["bankrupt", "形", "破産した", "The retailer went bankrupt last year.", "その小売業者は昨年破産した。"],
  ["benchmark", "名", "基準、指標", "The figures serve as a benchmark for future sales.", "その数値が今後の売上の基準となる。"],
  ["bid", "名", "入札、付け値", "Three firms submitted bids for the project.", "3社がその事業に入札した。"],
  ["blueprint", "名", "設計図、青写真", "The plan serves as a blueprint for growth.", "その計画は成長のための青写真となる。"],
  ["bolster", "動", "強化する、後押しする", "The campaign bolstered the brand's reputation.", "そのキャンペーンはブランドの評判を高めた。"],
  ["brisk", "形", "（商売が）活発な、好調な", "Sales have been brisk since the holiday season began.", "休暇シーズンが始まってから売れ行きは好調だ。"],
  ["buoyant", "形", "（景気が）好調な、活気のある", "The housing market remains buoyant.", "住宅市場は依然として好調だ。"],
  ["bureaucracy", "名", "官僚主義、お役所仕事", "Excessive bureaucracy slows decision-making.", "過度な官僚主義は意思決定を遅らせる。"],
  ["bylaw", "名", "（団体の）内規、細則", "The bylaws require an annual meeting.", "内規により年1回の総会が義務付けられている。"],
  ["capitalize", "動", "（on 〜を）活用する、つけ込む", "We should capitalize on this trend.", "この流行をうまく活用すべきだ。"],
  ["caterer", "名", "仕出し業者、ケータリング業者", "The caterer will arrive at noon.", "ケータリング業者は正午に到着する。"],
  ["cessation", "名", "停止、中止", "The cessation of production affected suppliers.", "生産停止は納入業者に影響を与えた。"],
  ["circumvent", "動", "回避する、うまく避ける", "They tried to circumvent the new regulations.", "彼らは新しい規制を回避しようとした。"],
  ["clientele", "名", "（集合的に）顧客層", "The boutique has a loyal clientele.", "そのブティックには固定客がついている。"],
  ["cognizant", "形", "認識している、気づいている", "Managers must be cognizant of safety risks.", "管理職は安全上のリスクを認識していなければならない。"],
  ["coherent", "形", "首尾一貫した、筋の通った", "We need a coherent marketing strategy.", "一貫したマーケティング戦略が必要だ。"],
  ["coincide", "動", "同時に起こる、一致する", "The sale coincides with the holiday weekend.", "セールは連休と重なる。"],
  ["collateral", "名", "担保", "The building was used as collateral for the loan.", "その建物が融資の担保にされた。"],
  ["commence", "動", "開始する", "Construction will commence in April.", "工事は4月に始まる。"],
  ["commensurate", "形", "（〜に）見合った、釣り合った", "Salary will be commensurate with experience.", "給与は経験に見合った額となる。"],
  ["commodity", "名", "商品、一次産品", "Coffee is one of the most traded commodities.", "コーヒーは最も取引量の多い商品の一つだ。"],
  ["compile", "動", "（資料を）まとめる、編集する", "She compiled a list of potential clients.", "彼女は見込み客のリストを作成した。"],
  ["compliance", "名", "（法令）遵守", "All branches must ensure compliance with local laws.", "全支店は現地の法律の遵守を徹底しなければならない。"],
  ["complimentary", "形", "無料の；称賛の", "Guests receive a complimentary breakfast.", "宿泊客には無料の朝食が付く。"],
  ["concession", "名", "譲歩；営業権", "The union won several concessions from management.", "組合は経営陣からいくつかの譲歩を引き出した。"],
  ["concise", "形", "簡潔な", "Keep the report concise and clear.", "報告書は簡潔明瞭にしてください。"],
  ["concur", "動", "同意する、意見が一致する", "The committee concurred with the recommendation.", "委員会はその勧告に同意した。"],
  ["conducive", "形", "（〜に）役立つ、助けとなる", "A quiet office is conducive to concentration.", "静かなオフィスは集中の助けとなる。"],
  ["conglomerate", "名", "複合企業、コングロマリット", "The brand is owned by a large conglomerate.", "そのブランドは大手複合企業の傘下にある。"],
  ["consecutive", "形", "連続した", "Profits rose for five consecutive quarters.", "利益は5四半期連続で増加した。"],
  ["consignment", "名", "委託（販売）；発送品", "The goods are sold on consignment.", "その商品は委託販売されている。"],
  ["consolidate", "動", "統合する、強化する", "The two departments will be consolidated next year.", "2つの部署は来年統合される。"],
  ["constituent", "名", "構成要素；有権者", "Each constituent of the product is tested.", "製品の各構成要素は検査される。"],
  ["contend", "動", "主張する；競う", "Critics contend that the price is too high.", "批評家たちは価格が高すぎると主張している。"],
  ["contingency", "名", "不測の事態", "We have a contingency plan in case of a power failure.", "停電に備えた緊急時対応計画がある。"],
  ["contingent", "形", "（on 〜）次第の、条件とする", "The offer is contingent on a background check.", "採用内定は経歴確認を条件とする。"],
  ["convene", "動", "（会議を）招集する、開く", "The board will convene next Thursday.", "取締役会は来週木曜日に開かれる。"],
  ["conversely", "副", "逆に、反対に", "Conversely, costs fell in the second quarter.", "逆に、第2四半期にはコストが下がった。"],
  ["cordial", "形", "心のこもった、友好的な", "The negotiations were cordial.", "交渉は友好的な雰囲気で進んだ。"],
  ["corroborate", "動", "裏付ける、確証する", "The data corroborate our findings.", "そのデータは我々の調査結果を裏付けている。"],
  ["counterpart", "名", "（別組織で）同等の立場の人", "He met his Korean counterpart in Seoul.", "彼はソウルで韓国側の担当者と会った。"],
  ["credential", "名", "資格、経歴、証明書", "Please submit your credentials by Friday.", "金曜日までに資格証明書を提出してください。"],
  ["critique", "名", "批評、評論", "The editor gave a detailed critique of the draft.", "編集者は原稿を詳細に批評した。"],
  ["culminate", "動", "最高潮に達する、ついに〜となる", "Months of talks culminated in a merger.", "数か月の協議はついに合併に至った。"],
  ["cumulative", "形", "累積の、累計の", "Cumulative sales passed one million units.", "累計販売台数は100万台を超えた。"],
  ["curtail", "動", "削減する、切り詰める", "The company curtailed its travel budget.", "会社は出張予算を削減した。"],
  ["deduct", "動", "差し引く、控除する", "Taxes are deducted from your salary.", "税金は給与から差し引かれる。"],
  ["deem", "動", "（〜と）みなす、考える", "The proposal was deemed too costly.", "その提案は費用がかかりすぎると判断された。"],
  ["defect", "名", "欠陥、不具合", "Every unit is inspected for defects.", "全製品について欠陥がないか検査される。"],
  ["defer", "動", "延期する；（判断を人に）委ねる", "Payment can be deferred until the end of the quarter.", "支払いは四半期末まで延期できる。"],
  ["deficit", "名", "赤字、不足額", "The company reported a budget deficit.", "会社は予算の赤字を報告した。"],
  ["delegate", "動", "（権限・仕事を）委任する", "Good managers delegate tasks effectively.", "優秀な管理職は仕事をうまく任せる。"],
  ["deliberate", "形", "意図的な、慎重な", "It was a deliberate decision to delay the launch.", "発売を遅らせたのは意図的な判断だった。"],
  ["delinquent", "形", "（支払いが）滞っている", "Delinquent accounts will be charged a late fee.", "支払いが滞っている口座には延滞料が課される。"],
  ["demographic", "名", "（特定の）購買層、人口層", "The ad targets a younger demographic.", "その広告は若年層を対象としている。"],
  ["deplete", "動", "使い果たす、激減させる", "Our stock of brochures is almost depleted.", "パンフレットの在庫がほぼ尽きている。"],
  ["depreciation", "名", "減価償却；価値の下落", "Depreciation is recorded as an annual expense.", "減価償却は年間費用として計上される。"],
  ["designate", "動", "指定する、任命する", "Smoking is allowed only in designated areas.", "喫煙は指定区域でのみ許可されている。"],
  ["deteriorate", "動", "悪化する", "Market conditions deteriorated in the second half.", "下半期に市況が悪化した。"],
  ["detrimental", "形", "有害な、不利益な", "Poor reviews can be detrimental to sales.", "悪い評価は売上に悪影響を与えうる。"],
  ["deviate", "動", "（from 〜から）逸脱する", "Do not deviate from the approved budget.", "承認済みの予算から逸脱しないこと。"],
  ["diligent", "形", "勤勉な、念入りな", "She is a diligent and reliable employee.", "彼女は勤勉で信頼できる社員だ。"],
  ["diminish", "動", "減少する、減らす", "Demand for the old model has diminished.", "旧モデルの需要は減少している。"],
  ["disburse", "動", "支出する、支払う", "The grant will be disbursed in two installments.", "助成金は2回に分けて支払われる。"],
  ["disclose", "動", "開示する、公表する", "The company did not disclose the price.", "会社は価格を公表しなかった。"],
  ["discontinue", "動", "（製造・サービスを）中止する", "This model has been discontinued.", "このモデルは製造中止になった。"],
  ["discrepancy", "名", "食い違い、不一致", "There is a discrepancy between the invoice and the order.", "請求書と注文書の間に食い違いがある。"],
  ["discretion", "名", "裁量、判断の自由", "Bonuses are paid at the manager's discretion.", "賞与は部長の裁量で支払われる。"],
  ["disparity", "名", "格差、相違", "There is a disparity in wages between regions.", "地域間で賃金格差がある。"],
  ["dispatch", "動", "発送する、派遣する", "Orders are dispatched within 24 hours.", "注文品は24時間以内に発送される。"],
  ["disposable", "形", "使い捨ての；（収入が）自由に使える", "Disposable income has risen this year.", "今年は可処分所得が増加した。"],
  ["disruption", "名", "混乱、中断", "The strike caused major disruptions to service.", "ストライキで運行に大きな乱れが生じた。"],
  ["disseminate", "動", "（情報を）広める、普及させる", "The findings were disseminated to all branches.", "調査結果は全支店に周知された。"],
  ["diversify", "動", "多角化する", "The firm diversified into healthcare.", "その企業は医療分野へ事業を多角化した。"],
  ["divest", "動", "（事業・資産を）売却する、手放す", "The firm plans to divest its retail division.", "その企業は小売部門を売却する予定だ。"],
  ["dividend", "名", "（株の）配当", "Shareholders will receive a higher dividend.", "株主はより多くの配当を受け取る。"],
  ["dormant", "形", "休止中の、眠っている", "The account has been dormant for two years.", "その口座は2年間使われていない。"],
  ["downsize", "動", "（人員・規模を）縮小する", "The plant was downsized last year.", "その工場は昨年規模を縮小した。"],
  ["dwindle", "動", "次第に減少する", "Our supply of paper is dwindling.", "用紙の在庫が少なくなってきている。"],
  ["elicit", "動", "（反応・情報を）引き出す", "The survey elicited valuable feedback.", "その調査から貴重な意見が得られた。"],
  ["eligible", "形", "資格のある、適格な", "Full-time staff are eligible for the bonus.", "正社員は賞与の対象となる。"],
  ["embargo", "名", "禁輸措置；報道禁止", "The government lifted the trade embargo.", "政府は貿易禁止措置を解除した。"],
  ["eminent", "形", "著名な、高名な", "An eminent economist will give the keynote.", "著名な経済学者が基調講演を行う。"],
  ["enclosure", "名", "同封物", "Please see the enclosure for details.", "詳細は同封の書類をご覧ください。"],
  ["encompass", "動", "包含する、網羅する", "The role encompasses both sales and marketing.", "その職務は営業とマーケティングの両方を含む。"],
  ["endeavor", "名", "努力、試み", "We wish you success in all your endeavors.", "今後のご活躍をお祈りします。"],
  ["endorse", "動", "支持する；（小切手に）裏書きする", "The board endorsed the proposal unanimously.", "取締役会は満場一致でその提案を支持した。"],
  ["enforce", "動", "（法律を）施行する、強制する", "The new rules will be strictly enforced.", "新しい規則は厳格に施行される。"],
  ["entail", "動", "（必然的に）伴う", "The position entails frequent travel.", "その職には頻繁な出張が伴う。"],
  ["entitle", "動", "権利・資格を与える", "This coupon entitles you to a free drink.", "このクーポンで飲み物が1杯無料になります。"],
  ["entrepreneur", "名", "起業家", "The event brings together young entrepreneurs.", "そのイベントには若い起業家が集まる。"],
  ["equitable", "形", "公平な、公正な", "We seek an equitable solution for both sides.", "双方にとって公平な解決策を求めている。"],
  ["erratic", "形", "不規則な、不安定な", "The machine's performance has been erratic.", "その機械の動作が不安定だ。"],
  ["escalate", "動", "段階的に拡大する、悪化する", "Costs escalated during construction.", "建設中に費用が膨らんだ。"],
  ["exacerbate", "動", "（問題を）悪化させる", "The shortage was exacerbated by the storm.", "嵐によって品不足がさらに悪化した。"],
  ["exemplary", "形", "模範的な", "She was praised for her exemplary service.", "彼女は模範的な働きぶりを称賛された。"],
  ["exempt", "形", "（from 〜を）免除された", "Small businesses are exempt from the tax.", "小規模事業者はその税を免除されている。"],
  ["exorbitant", "形", "法外な、途方もない", "Hotel rates are exorbitant during the festival.", "祭りの期間中、ホテル料金は法外に高い。"],
  ["expedite", "動", "迅速に処理する、早める", "Could you expedite the shipment?", "発送を急いでいただけますか。"],
  ["expenditure", "名", "支出、経費", "Capital expenditure will increase next year.", "来年は設備投資が増える。"],
  ["exponentially", "副", "急激に、指数関数的に", "Online orders grew exponentially.", "オンライン注文が急激に増加した。"],
  ["fabricate", "動", "製造する、組み立てる；でっち上げる", "The parts are fabricated in our factory.", "部品は自社工場で製造されている。"],
  ["facilitate", "動", "促進する、円滑にする", "The software facilitates communication.", "そのソフトは意思疎通を円滑にする。"],
  ["feasible", "形", "実現可能な", "The engineers confirmed the plan is feasible.", "技術者たちはその計画が実現可能だと確認した。"],
  ["fiscal", "形", "会計の、財政の", "The fiscal year ends on March 31.", "会計年度は3月31日に終わる。"],
  ["fluctuate", "動", "変動する", "Fuel prices fluctuate from month to month.", "燃料価格は月ごとに変動する。"],
  ["forfeit", "動", "（権利などを）失う、没収される", "Late applicants will forfeit their deposit.", "申込みが遅れた人は手付金を失う。"],
  ["forthcoming", "形", "近く予定されている；率直な", "Details will be announced in a forthcoming newsletter.", "詳細は次号のニュースレターで発表される。"],
  ["foster", "動", "育成する、促進する", "The program fosters collaboration between teams.", "その制度はチーム間の協力を促進する。"],
  ["freight", "名", "貨物、運送料", "Freight charges are included in the price.", "運送料は価格に含まれている。"],
  ["fulfill", "動", "（注文・義務を）果たす、処理する", "We fulfill most orders within two days.", "ほとんどの注文を2日以内に処理している。"],
  ["garner", "動", "（支持・注目を）獲得する", "The product garnered positive reviews.", "その製品は好意的な評価を得た。"],
  ["grievance", "名", "苦情、不満", "Employees may file a grievance with HR.", "従業員は人事部に苦情を申し立てられる。"],
  ["hamper", "動", "妨げる、阻む", "Heavy snow hampered the delivery schedule.", "大雪で配送予定に支障が出た。"],
  ["hinder", "動", "妨げる、遅らせる", "Lack of funding hindered the research.", "資金不足が研究の妨げとなった。"],
  ["hospitality", "名", "もてなし；接客業", "Thank you for your warm hospitality.", "温かいおもてなしに感謝します。"],
  ["impeccable", "形", "申し分のない、完璧な", "The hotel is known for its impeccable service.", "そのホテルは申し分のないサービスで知られている。"],
  ["impending", "形", "差し迫った", "Staff were informed of the impending merger.", "従業員は差し迫った合併について知らされた。"],
  ["imperative", "形", "必須の、極めて重要な", "It is imperative that we act quickly.", "迅速に行動することが不可欠だ。"],
  ["impose", "動", "（税・規則を）課す", "The city imposed a fee on plastic bags.", "市はレジ袋を有料化した。"],
  ["inadvertently", "副", "うっかり、不注意で", "The file was inadvertently deleted.", "そのファイルはうっかり削除されてしまった。"],
  ["inaugural", "形", "第1回の；就任の", "The inaugural conference drew 500 attendees.", "第1回の会議には500人が参加した。"],
  ["incidental", "形", "付随的な、付帯的な", "Incidental expenses will be reimbursed.", "付随的な経費は払い戻される。"],
  ["inclement", "形", "（天候が）荒れた、悪い", "The event will be held indoors in case of inclement weather.", "悪天候の場合、イベントは屋内で行われる。"],
  ["incumbent", "名", "現職者", "The incumbent will retire at the end of the year.", "現職者は年末に退職する。"],
  ["incur", "動", "（費用・損失を）負担する、被る", "The company incurred heavy losses.", "その会社は大きな損失を被った。"],
  ["indemnify", "動", "補償する、賠償する", "The contractor agrees to indemnify the client for any losses.", "請負業者はいかなる損失も顧客に補償することに同意する。"],
  ["indispensable", "形", "不可欠な", "She has become indispensable to the team.", "彼女はチームに欠かせない存在になった。"],
  ["influx", "名", "流入、殺到", "The hotel expects an influx of tourists.", "ホテルは観光客の殺到を見込んでいる。"],
  ["infrastructure", "名", "基盤、インフラ", "The city is investing in its infrastructure.", "市はインフラに投資している。"],
  ["infringe", "動", "（権利を）侵害する", "The design infringes on our patent.", "そのデザインは当社の特許を侵害している。"],
  ["inherent", "形", "本来備わった、固有の", "There are risks inherent in any investment.", "どんな投資にも固有のリスクがある。"],
  ["initiative", "名", "（新たな）取り組み；主導権", "The recycling initiative was a success.", "リサイクルの取り組みは成功した。"],
  ["insolvent", "形", "支払不能の、債務超過の", "The supplier was declared insolvent.", "その納入業者は支払不能と宣告された。"],
  ["installment", "名", "分割払い（の1回分）", "You can pay in six monthly installments.", "6回の月賦で支払える。"],
  ["integral", "形", "不可欠な、必須の", "Customer service is integral to our success.", "顧客サービスは当社の成功に不可欠だ。"],
  ["intermittent", "形", "断続的な", "Intermittent rain is expected this afternoon.", "今日の午後は断続的に雨が降る見込みだ。"],
  ["intricate", "形", "複雑な、入り組んだ", "The contract contains intricate clauses.", "その契約には複雑な条項が含まれている。"],
  ["invaluable", "形", "非常に貴重な", "Your advice has been invaluable.", "あなたの助言はとても貴重でした。"],
  ["inventory", "名", "在庫；棚卸し", "We take inventory at the end of each month.", "毎月末に棚卸しを行う。"],
  ["irrevocable", "形", "取り消し不能な", "Once signed, the agreement is irrevocable.", "署名後、その合意は取り消せない。"],
  ["itemize", "動", "項目別に記載する", "Please itemize your travel expenses.", "出張経費を項目別に記載してください。"],
  ["jeopardize", "動", "危険にさらす、危うくする", "Delays could jeopardize the contract.", "遅延は契約を危うくしかねない。"],
  ["lapse", "動", "（権利・契約が）失効する", "Your membership will lapse if not renewed.", "更新しないと会員資格は失効します。"],
  ["lenient", "形", "寛大な、甘い", "The return policy is quite lenient.", "返品規定はかなり寛大だ。"],
  ["leverage", "動", "活用する、てこにする", "We can leverage our network to find partners.", "人脈を活用して提携先を探せる。"],
  ["levy", "動", "（税を）課す、徴収する", "A new tax will be levied on imports.", "輸入品に新たな税が課される。"],
  ["liability", "名", "（法的）責任；負債", "The company accepted liability for the damage.", "会社はその損害に対する責任を認めた。"],
  ["liaison", "名", "連絡係、橋渡し役", "She acts as a liaison between the two offices.", "彼女は2つの事務所間の連絡係を務めている。"],
  ["liquidate", "動", "清算する、（資産を）現金化する", "The company was forced to liquidate its assets.", "その会社は資産の現金化を余儀なくされた。"],
  ["lodge", "動", "（苦情などを）正式に申し立てる", "Several customers lodged complaints.", "複数の顧客が正式に苦情を申し立てた。"],
  ["logistics", "名", "物流、実施計画", "He manages logistics for the event.", "彼はイベントの段取りを管理している。"],
  ["lucrative", "形", "もうかる、利益の大きい", "The contract proved extremely lucrative.", "その契約は非常に利益の大きいものとなった。"],
  ["mandatory", "形", "義務的な、必須の", "Attendance at the training is mandatory.", "研修への出席は必須である。"],
  ["manifest", "動", "明らかにする、表す", "The problem manifested itself in low sales.", "問題は売上の低迷という形で表れた。"],
  ["markup", "名", "値入れ、利幅", "The retailer applies a 40 percent markup.", "その小売店は40%の利幅を乗せている。"],
  ["memorandum", "名", "覚書、社内連絡", "A memorandum was sent to all employees.", "全従業員に社内連絡が送られた。"],
  ["merger", "名", "（企業の）合併", "The merger created the largest bank in the region.", "その合併で地域最大の銀行が誕生した。"],
  ["meticulous", "形", "細心の、きわめて注意深い", "He keeps meticulous records of every transaction.", "彼はすべての取引を細かく記録している。"],
  ["mitigate", "動", "軽減する、和らげる", "Insurance helps mitigate financial risk.", "保険は財務上のリスクを軽減するのに役立つ。"],
  ["monopoly", "名", "独占、専売", "The company holds a monopoly on the market.", "その会社は市場を独占している。"],
  ["moratorium", "名", "一時停止、猶予期間", "The city imposed a moratorium on new construction.", "市は新規建設を一時停止した。"],
  ["negligible", "形", "ごくわずかな、無視できる", "The impact on profits was negligible.", "利益への影響はごくわずかだった。"],
  ["niche", "名", "すき間市場、適所", "The firm found a profitable niche.", "その会社は収益性の高いすき間市場を見つけた。"],
  ["nominal", "形", "わずかな；名目上の", "A nominal fee is charged for parking.", "駐車にはわずかな料金がかかる。"],
  ["notwithstanding", "前", "〜にもかかわらず", "Notwithstanding the delay, the launch was a success.", "遅延にもかかわらず、発売は成功した。"],
  ["novice", "名", "初心者", "The course is designed for novices.", "その講座は初心者向けだ。"],
  ["obligatory", "形", "義務的な", "Safety training is obligatory for new staff.", "新入社員には安全研修が義務付けられている。"],
  ["obsolete", "形", "時代遅れの、廃れた", "The old software is now obsolete.", "古いソフトウェアはもう時代遅れだ。"],
  ["omission", "名", "省略、記載漏れ", "Please forgive the omission of your name.", "お名前の記載漏れをお許しください。"],
  ["onerous", "形", "負担の重い、厄介な", "The reporting requirements are onerous for small firms.", "その報告義務は小企業には負担が重い。"],
  ["optimal", "形", "最適な", "We are looking for the optimal location.", "最適な立地を探している。"],
  ["outlay", "名", "支出、経費", "The initial outlay was recovered within a year.", "初期費用は1年以内に回収された。"],
  ["outsource", "動", "外部委託する", "The firm outsources its payroll.", "その会社は給与計算を外部に委託している。"],
  ["outstanding", "形", "未払いの；傑出した", "Please settle the outstanding balance.", "未払い残高を精算してください。"],
  ["overdue", "形", "期限を過ぎた、延滞した", "The library book is two weeks overdue.", "図書館の本の返却期限が2週間過ぎている。"],
  ["overhaul", "動", "徹底的に見直す、分解修理する", "The firm overhauled its hiring process.", "その会社は採用手続きを全面的に見直した。"],
  ["oversee", "動", "監督する、統括する", "She oversees the Asian operations.", "彼女はアジア事業を統括している。"],
  ["paramount", "形", "最も重要な", "Customer safety is paramount.", "顧客の安全が最優先である。"],
  ["patronage", "名", "（顧客の）愛顧、ひいき", "Thank you for your continued patronage.", "引き続きのご愛顧に感謝いたします。"],
  ["payroll", "名", "給与支払い（名簿）、従業員数", "The company has 200 people on its payroll.", "その会社には200人の従業員がいる。"],
  ["pending", "形", "未決定の、保留中の", "The decision is pending approval from headquarters.", "その決定は本社の承認待ちである。"],
  ["periodical", "名", "定期刊行物", "The library subscribes to many periodicals.", "図書館は多くの定期刊行物を購読している。"],
  ["perishable", "形", "腐りやすい", "Perishable goods must be refrigerated.", "生鮮品は冷蔵しなければならない。"],
  ["perk", "名", "（給与以外の）特典", "Free lunch is one of the perks of the job.", "無料の昼食はその仕事の特典の一つだ。"],
  ["persevere", "動", "粘り強く続ける", "The team persevered despite setbacks.", "チームは挫折にもめげずやり抜いた。"],
  ["pertinent", "形", "関連のある、適切な", "Please bring all pertinent documents.", "関連する書類をすべてお持ちください。"],
  ["pharmaceutical", "形", "製薬の、薬学の", "She works for a pharmaceutical company.", "彼女は製薬会社に勤めている。"],
  ["pinpoint", "動", "正確に特定する", "Engineers pinpointed the source of the leak.", "技術者たちは漏れの原因を特定した。"],
  ["pivotal", "形", "極めて重要な、中心的な", "He played a pivotal role in the negotiations.", "彼は交渉で中心的な役割を果たした。"],
  ["plausible", "形", "もっともらしい、妥当な", "That is a plausible explanation.", "それは妥当な説明だ。"],
  ["plummet", "動", "急落する", "Share prices plummeted after the announcement.", "発表後、株価は急落した。"],
  ["precedent", "名", "前例、先例", "The ruling set an important precedent.", "その判決は重要な前例となった。"],
  ["predominantly", "副", "主に、大部分は", "Our customers are predominantly students.", "当店の客は主に学生だ。"],
  ["preliminary", "形", "予備の、準備段階の", "Preliminary results will be released next week.", "速報値は来週発表される。"],
  ["premises", "名", "敷地、構内、店内", "Smoking is prohibited on the premises.", "敷地内は禁煙です。"],
  ["prerequisite", "名", "前提条件、必須条件", "A valid license is a prerequisite for the job.", "有効な免許がその仕事の必須条件だ。"],
  ["prestigious", "形", "名門の、一流の", "She graduated from a prestigious university.", "彼女は名門大学を卒業した。"],
  ["prevail", "動", "普及している；勝る", "Optimism prevailed at the meeting.", "会議では楽観的な空気が支配的だった。"],
  ["principal", "形", "主要な、第一の", "The principal reason for the delay was weather.", "遅延の主な理由は天候だった。"],
  ["probationary", "形", "試用期間の", "New employees serve a three-month probationary period.", "新入社員は3か月の試用期間がある。"],
  ["proceeds", "名", "収益金、売上金", "Proceeds from the event go to charity.", "イベントの収益金は慈善事業に寄付される。"],
  ["procurement", "名", "調達、購買", "She works in the procurement department.", "彼女は調達部門で働いている。"],
  ["proficient", "形", "熟達した、堪能な", "Applicants must be proficient in English.", "応募者は英語に堪能でなければならない。"],
  ["profound", "形", "重大な、深い", "The merger had a profound impact on staff.", "合併は従業員に大きな影響を与えた。"],
  ["prohibitive", "形", "（価格が）法外な、手が出ない", "The cost of the upgrade is prohibitive.", "アップグレード費用は手が出ないほど高い。"],
  ["prominent", "形", "著名な；目立つ", "A prominent architect designed the building.", "著名な建築家がその建物を設計した。"],
  ["proprietary", "形", "専有の、独自の", "The company uses proprietary software.", "その会社は自社独自のソフトウェアを使っている。"],
  ["prospective", "形", "見込みのある、将来の", "We are meeting with prospective clients.", "見込み客と打ち合わせをする予定だ。"],
  ["prospectus", "名", "（事業の）案内書、目論見書", "Investors should read the prospectus carefully.", "投資家は目論見書をよく読むべきだ。"],
  ["prosperous", "形", "繁栄している、裕福な", "The town became prosperous after the port opened.", "港の開港後、町は繁栄した。"],
  ["provision", "名", "（契約の）条項；供給", "The contract includes a provision for early termination.", "契約には中途解約に関する条項がある。"],
  ["provisional", "形", "暫定的な、仮の", "A provisional schedule has been circulated.", "暫定的な予定表が配布された。"],
  ["proximity", "名", "近いこと、近接", "The hotel's proximity to the station is convenient.", "そのホテルは駅に近くて便利だ。"],
  ["quarterly", "形", "四半期ごとの", "Quarterly earnings exceeded expectations.", "四半期の収益は予想を上回った。"],
  ["quota", "名", "ノルマ、割当量", "She exceeded her sales quota.", "彼女は販売ノルマを上回った。"],
  ["ratify", "動", "批准する、正式に承認する", "Shareholders ratified the agreement.", "株主はその合意を正式に承認した。"],
  ["rationale", "名", "根拠、論理的理由", "Please explain the rationale for the change.", "変更の根拠を説明してください。"],
  ["realm", "名", "分野、領域", "That is outside the realm of our expertise.", "それは当社の専門分野外だ。"],
  ["rebate", "名", "（代金の一部）払い戻し", "Customers receive a rebate on energy-efficient models.", "省エネ型を購入した客は払い戻しを受けられる。"],
  ["receptive", "形", "（to 〜を）受け入れる", "Management was receptive to new ideas.", "経営陣は新しいアイデアを受け入れる姿勢だった。"],
  ["recession", "名", "景気後退", "Many firms cut jobs during the recession.", "景気後退期に多くの企業が人員を削減した。"],
  ["recipient", "名", "受取人、受賞者", "The recipient must sign for the package.", "受取人は荷物の受領に署名しなければならない。"],
  ["reciprocate", "動", "（好意に）報いる、返礼する", "We hope to reciprocate your kindness.", "ご厚意にお応えしたいと思います。"],
  ["reconcile", "動", "（帳簿を）照合する；和解させる", "Accountants reconcile the accounts every month.", "経理担当者は毎月勘定を照合する。"],
  ["recoup", "動", "（損失・費用を）取り戻す", "It will take years to recoup the investment.", "投資を回収するには何年もかかる。"],
  ["redeem", "動", "（クーポンなどを）引き換える", "Points can be redeemed for gift cards.", "ポイントはギフトカードと引き換えられる。"],
  ["redundant", "形", "余剰の、不要な；解雇された", "Fifty workers were made redundant.", "50人の従業員が解雇された。"],
  ["referral", "名", "紹介、照会", "Most of our clients come through referrals.", "顧客の大半は紹介によるものだ。"],
  ["refurbish", "動", "改装する、修復する", "The lobby was refurbished last year.", "ロビーは昨年改装された。"],
  ["reimburse", "動", "（経費を）払い戻す、弁済する", "Employees will be reimbursed for travel costs.", "従業員には交通費が払い戻される。"],
  ["reinforce", "動", "強化する、補強する", "The ad campaign reinforced brand loyalty.", "広告キャンペーンがブランドへの愛着を強めた。"],
  ["reiterate", "動", "繰り返し述べる", "The CEO reiterated his commitment to quality.", "CEOは品質重視の姿勢を改めて強調した。"],
  ["relinquish", "動", "（地位・権利を）手放す、放棄する", "He relinquished control of the company.", "彼は会社の経営権を手放した。"],
  ["relocate", "動", "移転する、転勤させる", "The office will relocate to Osaka.", "事務所は大阪に移転する。"],
  ["remedy", "名", "解決策、改善策", "We are seeking a remedy for the problem.", "その問題の解決策を探している。"],
  ["remittance", "名", "送金、送金額", "Please include the invoice number with your remittance.", "送金の際は請求書番号を記載してください。"],
  ["remuneration", "名", "報酬、給与", "Remuneration will be discussed at the interview.", "報酬については面接で話し合う。"],
  ["renowned", "形", "有名な、名高い", "The resort is renowned for its spa.", "そのリゾートはスパで有名だ。"],
  ["repercussion", "名", "（悪い）影響、反響", "The decision had serious repercussions.", "その決定は深刻な影響をもたらした。"],
  ["replenish", "動", "補充する", "Stock is replenished every Tuesday.", "在庫は毎週火曜日に補充される。"],
  ["reputable", "形", "評判のよい、信頼できる", "Always buy from a reputable dealer.", "必ず信頼できる販売店から購入してください。"],
  ["requisite", "形", "必要な、必須の", "Candidates must have the requisite skills.", "候補者は必要な技能を備えていなければならない。"],
  ["rescind", "動", "（決定・契約を）撤回する、取り消す", "The offer was rescinded due to budget cuts.", "予算削減によりその申し出は撤回された。"],
  ["residual", "形", "残りの、残留する", "Residual funds will be returned to donors.", "残余資金は寄付者に返還される。"],
  ["resilient", "形", "回復力のある、打たれ強い", "The economy has proved resilient.", "経済は回復力があることが証明された。"],
  ["respondent", "名", "（調査の）回答者", "Most respondents were satisfied with the service.", "回答者の大半はサービスに満足していた。"],
  ["restructure", "動", "再編する、再構築する", "The company plans to restructure its debt.", "会社は債務の再編を計画している。"],
  ["retention", "名", "保持；（人材の）定着", "Employee retention has improved this year.", "今年は従業員の定着率が改善した。"],
  ["revamp", "動", "刷新する、改良する", "The website was revamped last spring.", "ウェブサイトは昨春リニューアルされた。"],
  ["robust", "形", "堅調な、頑丈な", "The economy showed robust growth.", "経済は力強い成長を示した。"],
  ["salient", "形", "顕著な、重要な", "The report summarizes the salient points.", "報告書は重要な点を要約している。"],
  ["sanction", "名", "認可；（通例複数で）制裁", "The plan received official sanction.", "その計画は正式な認可を得た。"],
  ["scrutinize", "動", "精査する、詳しく調べる", "The auditors scrutinized every receipt.", "監査人はすべての領収書を精査した。"],
  ["seasoned", "形", "経験豊富な、熟練した", "She is a seasoned negotiator.", "彼女は経験豊富な交渉者だ。"],
  ["shareholder", "名", "株主", "Shareholders approved the merger.", "株主は合併を承認した。"],
  ["shortfall", "名", "不足（額）", "There is a shortfall of 2 million yen.", "200万円の不足がある。"],
  ["skeptical", "形", "懐疑的な", "Analysts remain skeptical about the forecast.", "アナリストはその予測に依然懐疑的だ。"],
  ["slated", "形", "（〜する）予定である", "The store is slated to open in June.", "その店は6月に開店する予定だ。"],
  ["solicit", "動", "（意見・寄付を）求める、募る", "We are soliciting feedback from customers.", "顧客からの意見を募集している。"],
  ["specification", "名", "仕様（書）", "The product meets all specifications.", "その製品はすべての仕様を満たしている。"],
  ["stagnant", "形", "停滞した、不振の", "Wages have remained stagnant for years.", "賃金は何年も横ばいのままだ。"],
  ["stakeholder", "名", "利害関係者", "We consulted all stakeholders before deciding.", "決定前にすべての利害関係者と協議した。"],
  ["stipulate", "動", "（契約で）規定する、明記する", "The contract stipulates a 30-day notice period.", "契約には30日前の通知期間が明記されている。"],
  ["streamline", "動", "合理化する、効率化する", "The new system will streamline ordering.", "新システムで発注業務が効率化される。"],
  ["stringent", "形", "厳しい、厳格な", "The factory meets stringent safety standards.", "その工場は厳しい安全基準を満たしている。"],
  ["subsequent", "形", "その後の、次の", "Subsequent meetings will be held online.", "以降の会議はオンラインで開催される。"],
  ["subsidiary", "名", "子会社", "The firm opened a subsidiary in Vietnam.", "その会社はベトナムに子会社を設立した。"],
  ["subsidize", "動", "補助金を出す", "The government subsidizes solar panels.", "政府は太陽光パネルに補助金を出している。"],
  ["substantial", "形", "かなりの、相当な", "The company made a substantial profit.", "その会社はかなりの利益を上げた。"],
  ["succinct", "形", "簡潔な", "Please keep your presentation succinct.", "発表は簡潔にまとめてください。"],
  ["supersede", "動", "取って代わる", "This version supersedes all previous ones.", "この版は以前のすべての版に代わるものだ。"],
  ["supplementary", "形", "補足の、追加の", "Supplementary materials are available online.", "補足資料はオンラインで入手できる。"],
  ["surge", "名", "急増、急騰", "There was a surge in online orders.", "オンライン注文が急増した。"],
  ["surpass", "動", "上回る、しのぐ", "Sales surpassed last year's record.", "売上は昨年の記録を上回った。"],
  ["surplus", "名", "余剰；黒字", "The budget showed a small surplus.", "予算にはわずかな黒字が出た。"],
  ["susceptible", "形", "（to 〜の）影響を受けやすい", "The region is susceptible to flooding.", "その地域は洪水の被害を受けやすい。"],
  ["sustainable", "形", "持続可能な", "We are committed to sustainable growth.", "当社は持続可能な成長に取り組んでいる。"],
  ["tangible", "形", "具体的な、目に見える；有形の", "The training produced tangible results.", "その研修は目に見える成果を生んだ。"],
  ["tariff", "名", "関税；料金表", "New tariffs were imposed on steel.", "鉄鋼に新たな関税が課された。"],
  ["tedious", "形", "退屈な、単調な", "Data entry can be tedious.", "データ入力は退屈なこともある。"],
  ["tentative", "形", "仮の、暫定的な", "We have a tentative agreement with the client.", "顧客と仮合意している。"],
  ["tenure", "名", "在職期間、任期", "During her tenure, sales doubled.", "彼女の在任中に売上は倍増した。"],
  ["terminate", "動", "終了させる、解除する", "Either party may terminate the contract.", "どちらの当事者も契約を解除できる。"],
  ["testimonial", "名", "推薦の言葉、お客様の声", "Read testimonials from satisfied customers.", "満足したお客様の声をご覧ください。"],
  ["thrive", "動", "繁栄する、成長する", "Small businesses thrive in this area.", "この地域では小規模事業が繁盛している。"],
  ["transcript", "名", "書き起こし；成績証明書", "A transcript of the speech is available.", "講演の書き起こしが入手できる。"],
  ["transparent", "形", "透明性のある、明白な", "The pricing is simple and transparent.", "価格設定は単純で分かりやすい。"],
  ["turnover", "名", "離職率；売上高", "High staff turnover increases training costs.", "高い離職率は研修費用を押し上げる。"],
  ["unanimous", "形", "満場一致の", "The vote was unanimous.", "採決は満場一致だった。"],
  ["undergo", "動", "（変化・検査を）受ける", "The building is undergoing renovation.", "その建物は改修中だ。"],
  ["underscore", "動", "強調する", "The results underscore the need for training.", "その結果は研修の必要性を浮き彫りにしている。"],
  ["undertake", "動", "引き受ける、着手する", "The firm undertook a major expansion.", "その会社は大規模な拡張に着手した。"],
  ["unprecedented", "形", "前例のない", "Demand reached an unprecedented level.", "需要は前例のない水準に達した。"],
  ["unveil", "動", "（新製品を）発表する、公開する", "The company will unveil its new phone tomorrow.", "その会社は明日新型スマホを発表する。"],
  ["upscale", "形", "高級な、富裕層向けの", "The restaurant is located in an upscale neighborhood.", "そのレストランは高級住宅街にある。"],
  ["utilize", "動", "利用する、活用する", "We need to utilize our resources better.", "資源をもっとうまく活用する必要がある。"],
  ["vendor", "名", "販売業者、納入業者", "We are reviewing proposals from three vendors.", "3社の納入業者からの提案を検討している。"],
  ["verbatim", "副", "一字一句そのまま", "The statement was quoted verbatim.", "その声明は一字一句そのまま引用された。"],
  ["versatile", "形", "多用途の、多才な", "This versatile tool has many uses.", "この万能な道具には多くの用途がある。"],
  ["viable", "形", "実行可能な、存続できる", "Remote work is a viable option for many roles.", "多くの職種で在宅勤務は現実的な選択肢だ。"],
  ["volatile", "形", "（価格が）不安定な、変動しやすい", "Oil prices remain volatile.", "原油価格は依然として不安定だ。"],
  ["voucher", "名", "割引券、引換券", "Each guest received a meal voucher.", "各宿泊客に食事券が配られた。"],
  ["waive", "動", "（権利・料金を）免除する、放棄する", "The bank agreed to waive the fee.", "銀行はその手数料を免除することに同意した。"],
  ["warrant", "動", "正当化する、必要とする", "The results warrant further investigation.", "その結果はさらなる調査に値する。"],
  ["warranty", "名", "（製品の）保証", "The printer comes with a two-year warranty.", "そのプリンターには2年保証が付いている。"],
  ["wholesale", "名", "卸売", "We buy products at wholesale prices.", "当社は卸値で商品を仕入れている。"],
  ["withhold", "動", "差し控える、保留する", "The client withheld payment until repairs were made.", "顧客は修理が済むまで支払いを保留した。"],
  ["yield", "動", "（利益・結果を）生む", "The investment yielded a high return.", "その投資は高い収益を生んだ。"]
];
